name: Rust

on: [push]

jobs:

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: nightly
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check --config-path <(echo 'license_template_path = "HEADER"')

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v2
      - run: cargo clippy -- --all-targets --all-features -- -D warnings

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - run: cargo check --all

  test:
    needs: [codestyle, lint, compile]
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: cargo test -- all-features
    - name: Coverage
      if: matrix.rust == 'stable'
      run: |
        # Tarpaulin interoperates with CI services, however Actions is not
        # currently supported. As a workaround, we can pretend to be Travis.
        export TRAVIS_JOB_ID=${GITHUB_SHA}
        export TRAVIS_PULL_REQUEST=false
        export TRAVIS_BRANCH=${GITHUB_REF##*/}
        cargo install cargo-tarpaulin
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
